language: java
sudo: false # false for faster builds
script: "mvn -Dmaven.javadoc.skip=false clean install cobertura:cobertura checkstyle:checkstyle pmd:pmd javadoc:javadoc javadoc:aggregate site"
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
